<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>LibreGuard.VpnService</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\LibreGuard VPN Desktop\Assets\Images\LibreGuard_logo_cropped_V3.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LibreGuard VPN Desktop.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibreGuard.VpnService.Contracts\LibreGuard.VpnService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
  </ItemGroup>

</Project>
